---
title: "Lab Data"
author: "Stephen Roecker"
date: "December 19, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
setwd("C:/Users/stephen.roecker/OneDrive - USDA/data/kssl")
```

# LDM Access

```{r access}

# only work in 32-bit R version

library(RODBC)
library(aqp)

# KSSL access database can be downloaded from https://ncsslabdatamart.sc.egov.usda.gov/
con <- odbcConnectAccess(access.file = "NCSS_Lab_Data_Mart_09142018.mdb")
(access_names <- sqlTables(con))
idx <- !grepl("MSys", access_names$TABLE_NAME)
ldm_access <- lapply(access_names$TABLE_NAME[idx], function(x) sqlFetch(con , x, as.is = TRUE))
names(ldm_access) <- access_names$TABLE_NAME[idx]
odbcClose(con)

l <- ldm_access


# horizon table
h <- merge(l$NCSS_Layer[c("labsampnum", "layer_key", "pedon_key", "hzn_desgn", "hzn_top", "hzn_bot")], 
           l$PSDA_and_Rock_Fragments[
             l$PSDA_and_Rock_Fragments$prep_code == "S", 
             c("labsampnum", "tex_psda", "clay_tot_psa", "silt_tot_psa", "sand_tot_psa")],
           by = "labsampnum",
           all.x = TRUE
           )
h <- merge(h,
           l$pH_and_Carbonates[
             l$pH_and_Carbonates$prep_code == "S",
             c("labsampnum", "ph_h2o")],
           by = "labsampnum",
           all.x = TRUE
           )
h <- merge(h, 
          l$Carbon_and_Extractions[
            l$Carbon_and_Extractions$prep_code == "S",
            c("labsampnum", "c_tot", "oc", "oc_code")],
          by = "labsampnum",
          all.x = TRUE
          )


# site table
s <- merge(l$NCSS_Pedon_Taxonomy[c("site_key", "pedon_key", "pedlabsampnum", "pedoniid", "samp_name", "corr_name", "samp_classdate", "corr_classdate")],
           l$NCSS_Site_Location[c("site_key", "siteiid", "latitude_decimal_degrees", "longitude_decimal_degrees", "county_code", "state_code")],
           by = "site_key",
           all.x = TRUE
           )
s$corr_classdate <- strptime(s$corr_classdate, format="%Y-%m-%d %H:%M:%S")
s <- s[order(s$corr_classdate, s$samp_classdate, decreasing = TRUE), ]
s <- s[complete.cases(s$latitude_decimal_degrees, s$longitude_decimal_degrees), ]
s <- s[!duplicated(s$pedlabsampnum), ]


# soil profile collection object
spc <- h
depths(spc) <- pedon_key ~ hzn_top + hzn_bot
site(spc) <- s
spc_access <- spc


# save(ldm_access, spc_access, file = "C:/Users/stephen.roecker/Nextcloud/data/ldm/NCSS_Lab_Data_Mart_20180914.RData")
# close and open 64-bit R version
load(file = "NCSS_Lab_Data_Mart_20180914.RData")

```



# LDM Sqlite

```{r sqlite}

# https://new.cloudvault.usda.gov/index.php/s/eSoPYbWDBQNX2HP

library(DBI)

con <- dbConnect(RSQLite::SQLite(), "C:/Users/steph/Nextcloud/data/ldm/LDM-compact_20200422.sqlite")
area <- read.csv("C:/Users/steph/Nextcloud/data/ldm/lab_area.txt", stringsAsFactors = FALSE)
dbCreateTable(con, "area", area)
(ldm_names <- dbListTables(con))
ldm <- lapply(ldm_names, function(x) dbReadTable(con , x))
names(ldm) <- ldm_names
dbDisconnect(con)



# horizon table
chem_vars <- c("labsampnum", "ec_predict_one_to_two", "ec_predict_one_to_two_method", "electrical_conductivity_satx", "electrical_cond_satx_method", "ph_h2o", "ph_h2o_method", "ph_saturated_paste", "exchangeable_sodium", "sodium_absorption_ratio", "total_estimated_salts_satx")
phys_vars <- c("labsampnum", "texture_lab", "clay_total", "silt_total", "sand_total", "total_frag_wt_pct_gt_2_mm_ws", "bulk_density_third_bar", "estimated_organic_matter")
l_vars <- c("labsampnum", "layer_key", "pedon_key", "hzn_desgn", "hzn_top", "hzn_bot", "texture_description", "stratified_textures_flag")

h <- merge(ldm$layer[l_vars],
           ldm$physical[! duplicated(ldm$physical$labsampnum), phys_vars],
           by = "labsampnum",
           all.x = TRUE
           )
h <- merge(h, 
           ldm$chemical[chem_vars],
           by = "labsampnum",
           all.x = TRUE
           )


# site table
ncss_vars <- c("site_key", "pedon_key", "pedlabsampnum", "pedoniid", "samp_name", "corr_name", "samp_classdate", "corr_classdate")
site_vars <- c("site_key", "user_site_id", "latitude_std_decimal_degrees", "longitude_std_decimal_degrees")

s <- merge(ldm$nasis_ncss[ncss_vars],
           ldm$nasis_site[site_vars],
           by = "site_key",
           all.x = TRUE
           )
s <- within(s, {
            samp_classdate = strptime(samp_classdate, format = "%Y-%m-%d %H:%M:%S")
            corr_classdate = strptime(corr_classdate, format="%Y-%m-%d %H:%M:%S")
            })
s <- s[with(s, order(corr_classdate, samp_classdate, decreasing = TRUE)), ]



# sf object
library(sf)
s_sf <- subset(s, complete.cases(latitude_std_decimal_degrees, longitude_std_decimal_degrees))
s_sf <- st_as_sf(s_sf, 
                 coords = c("longitude_std_decimal_degrees", "latitude_std_decimal_degrees"),
                 crs = 4326
                 )


# save(ldm, spc, s_sf, file = "C:/Users/stephen.roecker/Nextcloud/data/ldm/LDM-compact_20200422.RData")
load(file = "C:/Users/stephen.roecker/Nextcloud/data/ldm/LDM-compact_20200422.RData")

h_agg <- dplyr::group_by(h, pedon_key) %>% dplyr::summarize(n = length(layer_key), top = sum(hzn_top < 1), p = any(!is.na(ph_h2o)) & any(!is.na(clay_total))) %>% dplyr::ungroup() %>% dplyr::filter(n > 2 & top == 0 & p == TRUE)

```



# segment and spline

```{r}

# create intervals and point depths ----

# intervals
int <- as.integer(c(0, 5, 15, 30, 60, 100, 150))

# point depths
pnt <- {
  cbind(int[-length(int)],
        int[-1]
  ) ->.;
  as.integer(round(rowMeans(.)))
}

# point depth intervals
pnt_int <- as.integer(sort(c(pnt, pnt + 1)))



# check horizon logic and remove bad pedons ----
spc <- spc_access
spc$hzn_top <- round(spc$hzn_top)
spc$hzn_bot <- round(spc$hzn_bot)
idx <- checkHzDepthLogic(spc)
spc <- spc[which(site(spc)$pedon_key %in% idx[idx$valid == TRUE, ]$pedon_key), ]

spc$clay <- spc$clay_tot_psa
spc$silt <- spc$silt_tot_psa
spc$sand <- spc$sand_tot_psa
spc$pH   <- spc$ph_h2o

vars <- c("clay", "silt", "sand", "oc", "pH")



# depth intervals ----
# segment
spc_int <- segment(spc, intervals = int) 

# compute weighted averages
h_int_wa <- horizons(spc_int) %>%
  mutate(thk = hzn_bot - hzn_top) %>%
  group_by(pedon_key, segment_id) %>%
  summarize(
    clay_wa = weighted.mean(clay_tot_psa, w = thk, na.rm = TRUE),
    silt_wa = weighted.mean(silt_tot_psa, w = thk, na.rm = TRUE),
    sand_wa = weighted.mean(sand_tot_psa, w = thk, na.rm = TRUE),
    oc_wa   = weighted.mean(oc,           w = thk, na.rm = TRUE),
    ph_wa   = log10(weighted.mean(1/10^-ph_h2o, w = thk, na.rm = TRUE))
    ) %>%
  ungroup() %>%
  as.data.frame()
vars <- c("clay_wa", "silt_wa", "sand_wa", "oc_wa", "ph_wa")
h_int_wa_w <- reshape(data = h_int_wa, direction = "wide", 
                  idvar = "pedon_key", 
                  v.names = vars, 
                  timevar = "segment_id"
                  )
attributes(h_int_wa_w)$reshapeWide <- NULL
h_int_wa_w <- h_int_wa_w[!grepl(".NA$", names(h_int_wa_w))]



# point depths ----
# segment
spc_pnt <- segment(spc, intervals = pnt_int)
h <- horizons(spc_pnt)
idx <- which(as.integer(h$hzn_top) %in% as.integer(pnt))
h_pnt <- h[idx, c("pedon_key", "hzn_top", vars)]
h_pnt$depth <- paste0("dp_", formatC(h_pnt$hzn_top, width = 3, flag = "0"), "_cm")

h_pnt_w <- reshape(data = h_pnt[c("pedon_key", vars, "depth")], 
                   direction = "wide", 
                   idvar = "pedon_key", 
                   v.names = vars, 
                   timevar = "depth"
                   )
attributes(h_pnt_w)$reshapeWide <- NULL



# spline intervals ----
library(mpspline2)

# fit mp splines to properties
h_mps_l <- lapply(vars, function(x) {
  
  vars <- c("pedon_key", "hzn_top", "hzn_bot", x)
  h2 <- horizons(spc)[vars]
  h2 <- h2[which(complete.cases(h2)), ]

  mps <- mpspline(
    h2,
    var_name = x, 
    lam = 0.8, 
    d   = c(0, 5, 15, 30, 60, 100, 150)
    )
})
names(h_mps_l) <- vars
# saveRDS(h_mps_l, file = "h_mps_l.rds")
h_mps_l <- readRDS(file = "h_mps_l.rds")


# tidy and extract mp splines
h_mps_l_df <- lapply(vars, function(x, int = 1:6) {
  
  var_l <- s_mps_l[[x]]
  
  cat("tidying", x, "\n")
  
  # spline by depth interval
  dcm_df <- lapply(var_l, function(x2) {
    data.frame(pedon_key = x2$pedon_key, var = x2$est_dcm[int]) ->.;
    names(.)[2] <- x
    .$depths <- names(x2$est_dcm)[int]
    return(.)
  })
  dcm_df <- do.call("rbind", dcm_df)
  dcm_df$depths <- paste0("si_", dcm_df$depths)
    
  # tidyr::spread(mps_df, depths, var)
  dcm_df <- reshape(dcm_df,
                    direction = "wide",
                    idvar   = "pedon_key",
                    v.names = x,
                    timevar = "depths"
                    )
  attributes(dcm_df)$reshapeWide <- NULL
  
  # spline by 1cm increments
  cm_df <- lapply(var_l, function(x2) {
    data.frame(pedon_key = x2$pedon_key, var = x2$est_1cm) ->.;
    names(.)[2] <- x
    .$depths <- as.integer(1:length(x2$est_1cm) - 1)
    return(.)
  })
  cm_df <- do.call("rbind", cm_df)
  cm_df <- cm_df[cm_df$depths %in% pnt, ]
  cm_df$depths <- paste0("sp_", formatC(cm_df$depths, width = 3, flag = "0"), "_cm")
  
  # tidyr::spread(mps_df, depths, var)
  cm_df <- reshape(cm_df,
                    direction = "wide",
                    idvar   = "pedon_key",
                    v.names = x,
                    timevar = "depths"
                    )
  attributes(cm_df)$reshapeWide <- NULL
  
  
  df <- merge(dcm_df, cm_df, by = "pedon_key", all.x = TRUE)
  
  return(df)
  })
names(h_mps_l_df) <- vars
# saveRDS(h_mps_l_df, file = "h_mps_l_df.rds")
h_mps_l_df <- readRDS(file = "h_mps_l_df.rds")

h_df <- h_mps_l_df$clay %>%
  left_join(h_mps_l_df$silt, by = "pedon_key") %>%
  left_join(h_mps_l_df$sand, by = "pedon_key") %>%
  left_join(h_mps_l_df$oc,   by = "pedon_key") %>%
  left_join(h_mps_l_df$pH,   by = "pedon_key") %>%
  left_join(h_pnt_w,         by = "pedon_key") %>%
  left_join(h_int_wa_w,      by = "pedon_key")

h_df_long <- reshape(h_df, 
        direction = "long",
        timevar = "variable", times = names(h_df)[-1],
        v.names = "value",    varying = names(h_df)[-1]
        )

h_df_long <- within(h_df_long, {
  # parse method
  method = ifelse(grepl("sp", variable), "point",    NA)
  method = ifelse(grepl("dp", variable), "point",    method)
  method = ifelse(grepl("si", variable), "interval", method)
  method = ifelse(grepl("wa", variable), "interval", method)

  # parse source
  source = ifelse(grepl("sp", variable), "spline",   NA)
  source = ifelse(grepl("dp", variable), "original", source)
  source = ifelse(grepl("si", variable), "spline",   source)
  source = ifelse(grepl("wa", variable), "original", source)

  # parse depth interval
  dep_int  = ifelse(grepl("5_cm|5$|002_cm",     variable), "000-005", NA)
  dep_int  = ifelse(grepl("15_cm|15$|010_cm",   variable), "005-015", dep_int)
  dep_int  = ifelse(grepl("30_cm|30$|022_cm",   variable), "015-030", dep_int)
  dep_int  = ifelse(grepl("60_cm|60$|045_cm",   variable), "030-060", dep_int)
  dep_int  = ifelse(grepl("100_cm|100$|080_cm", variable), "060-100", dep_int)
  dep_int  = ifelse(grepl("150_cm|150$|125_cm", variable), "100-150", dep_int)
  dep_int  = factor(dep_int, levels = c("000-005", "005-015", "015-030", "030-060", "060-100", "100-150"))
  
  # parse variable
  var = sapply(variable, function(x) strsplit(x, "\\.|_")[[1]][1])
})

h_df_long$var <- tolower(h_df_long$var)
# save(h_df, h_df_long, file = "depth_comparisons.RData")

```


# comparison

```{r}

library(dplyr)
library(ggplot2)
library(knitr)

load(file = "depth_comparisons.RData")

test <- aggregate(value ~ var + method + source + dep_int, data = h_df_long[h_df_long$value > -0.1, ], function(x) {
  # cbind(round(fivenum(x, na.rm = TRUE)), length(x)[1])
round(summary(x)) 
    },
na.action = na.pass)

test2 <- aggregate(value ~ var + method + source + dep_int, data = h_df_long[h_df_long$value > -0.1, ], function(x) sum(!is.na(x)),
na.action = na.pass)

test3 <- cbind(test[1:3], test$value, n = test2$value)

aggregate(value ~ method, data = h_df_long[h_df_long$var == "clay" &  h_df_long$value > -1, ], function(x) var(x, na.rm = TRUE))

h_df_long %>%
  filter(var %in% c("ph") & value > 0 & pedon_key %in% s_ucrb$pedon_key) %>%
  ggplot(aes(x = value, y = paste(method, source))) +
  geom_boxplot() +
  # scale_x_log10() +
  facet_grid(var ~ dep_int, scales = "free_x")

test <- h_df_long %>%
  select(- variable, -id) %>%
  pivot_wider(names_from = c(source), values_fn = mean)

test %>%
  filter(var == "clay" & pedon_key %in% s_ucrb$pedon_key) %>%
  ggplot(aes(x = spline, y = original)) +
  geom_point() +
  geom_abline() +
  facet_grid(method ~ dep_int) +
  ggtitle("Clay (%)")

test %>%
  filter(var == "oc" & pedon_key %in% s_ucrb$pedon_key) %>%
  ggplot(aes(x = spline, y = original)) +
  geom_point() +
  geom_abline() +
  facet_grid(method ~ dep_int, scales = "free_x") +
  ggtitle("Organic Carbon (%)")


test <- h_df_long %>%
  select(- variable, -id) %>%
  pivot_wider(names_from = c(method), values_fn = mean)

test %>%
  filter(var == "clay" & pedon_key %in% s_ucrb$pedon_key) %>%
  ggplot(aes(x = interval, y = point)) +
  geom_point() +
  geom_abline() +
  facet_grid(source ~ dep_int) +
  ggtitle("clay")

test %>%
  filter(var == "oc" & pedon_key %in% s_ucrb$pedon_key) %>%
  ggplot(aes(x = interval, y = point)) +
  geom_point() +
  geom_abline() +
  facet_wrap(source ~ dep_int, scales = "free") +
  ggtitle("OC")


```


# spatial

```{r spatial}

library(sf)

s <- site(spc_access)
s_sf <- subset(s, complete.cases(latitude_decimal_degrees, longitude_decimal_degrees))
s_sf <- st_as_sf(s_sf, 
                 coords = c("longitude_decimal_degrees", "latitude_decimal_degrees"),
                 crs = 4326
                 )
s_sf <- st_transform(s_sf, crs = 5070)

# upper colorado river basin
ucrb <- read_sf(dsn = "C:/Users/Stephen.Roecker/Nextcloud/projects/2020_methodology_comparison", layer = "CO_River_watershed_Meade_alb")
ucrb <- st_transform(ucrb, 5070)


# sapolygon
ssa <- read_sf(dsn = "D:/geodata/soils/SSURGO_CONUS_FY19.gdb", layer = "SAPOLYGON", precision = 1)
ssa <- rmapshaper::ms_simplify(ssa)
# save(ssa, file = "D:/geodata/soils/SSURGO_CONUS_FY19_SAPOLYGON.RData")
load(file = "D:/geodata/soils/SSURGO_CONUS_FY19_SAPOLYGON.RData")
ssa <- st_transform(ssa, crs = 5070)
# ssa_b <- st_buffer(ssa, 10000)
bb <- st_bbox(ssa)


# states
library(USAboundaries)
st <- us_states()
st <- st_transform(st, 5070)


# nasis sites
s_sf <- {
  s ->.;
  subset(., complete.cases(x_std, y_std)) ->.; # & !is.na(pedlabsampnum)
  within(., {
    x = ifelse(is.na(x), x_std, x)
    y = ifelse(is.na(y), y_std, y)
    }) ->.;
  st_as_sf(., coords = c("x_std", "y_std"), crs = 4326) ->.;
  st_transform(., 5070) ->.;
  }


# ldm snapshot
l_sf <- {
  ldm$nasis_site ->.;
  # merge(ldm_access$NCSS_Pedon_Lab_Data, s, by.x = "user_pedon_id", by.y = "upedonid", all.x = TRUE) ->.;
  within(., {
    x_std = longitude_std_decimal_degrees
    y_std = latitude_std_decimal_degrees
    longitude_minutes = ifelse(is.na(longitude_minutes), 0, longitude_minutes)
    longitude_seconds = ifelse(is.na(longitude_seconds), 0, longitude_seconds)
    latitude_minutes  = ifelse(is.na(latitude_minutes),  0, latitude_minutes)
    latitude_seconds  = ifelse(is.na(latitude_seconds),  0, latitude_seconds)
    latdd = (longitude_degrees + longitude_minutes / 60 + longitude_seconds / 60) * -1
    londd =  latitude_degrees  + latitude_minutes  / 60 + latitude_seconds  / 60
    x_std = ifelse(is.na(x_std), londd, x_std)
    y_std = ifelse(is.na(y_std), latdd, y_std)
    }) ->.;
  subset(., complete.cases(x_std, y_std)) ->.;
  # subset(., complete.cases(x_std, y_std)) ->.;
  st_as_sf(.,
           coords = c("x_std", "y_std"),
           # coords = c("x_std", "y_std"), 
           crs = 4326
           ) ->.;
  st_transform(., 5070)
  }
table(substr(l_sf$areasymbol, 1, 2))

ldm_s <- merge(ldm$nasis_ncss, s[c("pedlabsampnum", "x", "y", "areasymbol", "utmzone", "utmeasting", "utmnorthing", "horizdatnm")], by = "pedlabsampnum", all.x = TRUE)
table(substr(ldm_s$areasymbol, 1, 2))[c("IL", "IN", "MI", "MN", "MO", "OH", "WI")]

ldm_s2 <- merge(ldm_s, ldm_access$NCSS_Site_Location[c("siteiid", "county_code")], by = "siteiid", all.x = TRUE)
ldm_s2 <- within(ldm_s2, {
  county_code = as.character(county_code)
  areasymbol  = ifelse(is.na(areasymbol), county_code, areasymbol)
})
ldm_s2 <- {
  ldm_s2 ->.;
  subset(., complete.cases(x, y)) ->.;
  st_as_sf(., coords = c("x", "y"), crs = 4326) ->.;
  st_transform(., 5070)
}

table(substr(ldm_s2$areasymbol, 1, 2))[c("IA", "IL", "IN", "MI", "MN", "MO", "OH", "WI")]
idx <- with(ldm_s2, !complete.cases(x, y))
table(substr(ldm_s2$areasymbol[idx], 1, 2))[c("IA", "IL", "IN", "MI", "MN", "OH", "WI")]

test3 = subset(ldm_s2, !complete.cases(x, y) & complete.cases(utmeasting, utmnorthing, utmzone, horizdatnm))


# ldm_access

s_sf <- st_as_sf(s,
                 coords = c("longitude_decimal_degrees", "latitude_decimal_degrees"),
                 crs = 4326
                 ) %>%
  st_transform(5070)
  
```



# intersect

```{r }

idx <- st_intersects(s_sf, st_buffer(ucrb, 10000), sparse = FALSE)
s_ucrb <- s_sf[idx[, 1], ]



# impute coordinates
idx <- with(ldm_s2, !complete.cases(latitude_decimal_degrees, longitude_decimal_degrees))

```



# Map

```{r map}

library(ggplot2)

st <- subset(st, ! state_name %in% c("Alaska", "Hawaii"))
bb <- st_bbox(ucrb)

s_ucrb$lab <- ifelse(!is.na(s_ucrb$pedlabsampnum), "KSSL", "field")


ggplot() +
  geom_sf(data = ucrb, fill = NA, col = "blue") +
  geom_sf(data = st, fill = NA) +
  geom_sf(data = s_ucrb, size = 0.00001, alpha = 0.15) +
  xlim(bb[c(1, 3)]) +
  ylim(bb[c(2, 4)]) +
  facet_wrap(~ lab) +
  # coord_sf(crs = "+init=epsg:5070") + 
  guides(fill = FALSE) +
  ggtitle("Location of Lab Data")

```


# CEC & ECEC for Alaska O Horizons

```{r}

library(dplyr)
library(ggplot2)

ldm <- ldm_access; rm(ldm_access)

ak <- ldm$NCSS_Site_Location[c("site_key", "mlra_code", "state_code")] %>%
  filter(state_code == "AK") %>%
  # left_join(ldm$NCSS_Pedon_Taxonomy[c("site_key", "pedlabsampnum")], by = "site_key") %>%
  left_join(ldm$NCSS_Layer[c("site_key", "labsampnum", "hzn_desgn")], by = "site_key") %>%
  left_join(ldm$CEC_and_Bases, by = "labsampnum") %>%
  filter(grepl("^O", hzn_desgn)) %>%
  filter(!grepl("A|B|C", hzn_desgn))

ak_cec <- ak %>%
  group_by(mlra_code) %>%
  summarize(cec_sum_min = min(cec_sum, na.rm = TRUE),
            cec_sum_25p = quantile(cec_sum, probs = 0.25, na.rm = TRUE),
            cec_sum_50p = quantile(cec_sum, probs = 0.5,  na.rm = TRUE),
            cec_sum_75p = quantile(cec_sum, probs = 0.75, na.rm = TRUE),
            cec_sum_max = max(cec_sum, na.rm = TRUE),
            cec_sum_n   = sum(!is.na(cec_sum)),
            ecec_min = min(ecec, na.rm = TRUE),
            ecec_25p = quantile(ecec, probs = 0.25, na.rm = TRUE),
            ecec_50p = quantile(ecec, probs = 0.5,  na.rm = TRUE),
            ecec_75p = quantile(ecec, probs = 0.75, na.rm = TRUE),
            ecec_max = max(ecec, na.rm = TRUE),
            ecec_n   = sum(!is.na(ecec))
            ) %>%
  ungroup() %>%
  filter(!is.na(cec_sum_50p) | !is.na(ecec_50p))
ak_cec[-1] <- lapply(ak_cec[-1], function(x) round(x, 1))


ak2 <- filter(ak, !is.na(cec_sum) | !is.na(ecec))
ak_long <- reshape2::melt(ak2, id.vars = "mlra_code", measure.vars = c("cec_sum", "ecec"))
ggplot(ak_long, aes(x = mlra_code, y = value)) +
  geom_boxplot() +
  facet_grid(~ variable, scales = "free_y") +
  coord_flip() +
  ggtitle("CEC and ECEC for Alaska O Horizons") +
  xlab("MLRA")

```